### PR TITLE
[FIX] Replacement for native JS types

### LINKED ISSUE #10: Don't replace native JS object like Date with ui5 sap/ui/model/type/Date
After migration the new Date() (native js) will be replaced with sap/ui/model/type/Date.

This should not be the case :)

All native datetime objects are not working anymore. By removing the define and parameter, the code works again.

### PR DESCRIPTION
**Pull request by tommyvinhlam**
Fixes #10

Variable names and parameter names now exclude js builtin types as well as browser globals.

### CODE REVIEW

**Comment by tommyvinhlam** [comment]
Test screnario:
```js
var oDate = new sap.ui.model.type.Date();
return oDate;
```
Result:
```js
var oDate = new oDate();
return oDate;
```
Ideally, the variable name should be replaced by parts of the namespace sap.ui.model.type.Date => TypeDate. But instead, the candidate gets prefixed with a single 'o' which is also not correct, as 'oDate' is already in use by "var oDate = ...". "ooDate" should have been the correct result...

File: src/util/VariableNameCreator.ts [hunk 1]
```diff
@@ -16,8 +16,84 @@ const reservedKeywords = [
...
+	"decodeURIComponent",
+	"encodeURI",
+	"encodeURIComponent",
+	"eval",
+	"globalThis",
+	"isFinite",
+	"isNaN",
+	"null",
+	"parseFloat",
+	"parseInt"
```
Comment (tobiasso85) [inline src/util/VariableNameCreator.ts]: also have a looks at:
`Object.keys(window).join(", ")`

Comment (codeworrior) [reply src/util/VariableNameCreator.ts]: I would rather rely on https://github.com/sindresorhus/globals .

Or, check k against the globals in each module. If `UInt8Array` is not used, why search for  another name?

Comment (matz3) [reply src/util/VariableNameCreator.ts]: +1 for using the `globals` package

Comment (tobiasso85) [reply src/util/VariableNameCreator.ts]: that's a neat module :) covered with c7c02ec

File: src/util/VariableNameCreator.ts [hunk 2]
```diff
@@ -17,69 +19,126 @@ const reservedKeywords = [
...
+};
 
-	// replace invalid chars
-	sVariableName = sVariableName.replace(rInvalidChars, "_");
 
-	// ensure there is no keyword match
-	while (reservedKeywords.includes(sVariableName) ||
-		   sapReservedKeywords.includes(sVariableName)) {
-		sVariableName = "o" + capitalize(sVariableName);
+const getUniqueName = function(
```
Comment (tommyvinhlam) [inline src/util/VariableNameCreator.ts]: Please add jsdoc, this would help to understand the prefixing

Comment (tommyvinhlam) [reply src/util/VariableNameCreator.ts]: Only when the whole namespace is still no valid variable name, the prefixing is taking place

File: test/util/VariableNameCreatorTest.ts [hunk 3]
```diff
@@ -39,4 +48,57 @@ describe("VariableNameCreator", function() {
 				[ "asdYeyYoo", "yeyYoo", "yoo" ], "asd.yey.yoo"),
 			"oAsdYeyYoo");
 	});
-});
\ No newline at end of file
+
+	it("getUniqueParameterName", function() {
+		assert.strictEqual(
```
Comment (tommyvinhlam) [inline test/util/VariableNameCreatorTest.ts]: Maybe add assertion texts for better understanding of the tests

File: src/util/VariableNameCreator.ts (hunk 2 above)
Comment (tobiasso85) [reply src/util/VariableNameCreator.ts]: ok

File: test/util/VariableNameCreatorTest.ts (hunk 3 above)
Comment (tobiasso85) [reply test/util/VariableNameCreatorTest.ts]: ok

**Comment by tommyvinhlam** [comment]
LGTM2
